apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.containerPort }}
    targetPort: {{ .Values.service.containerPort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.deployment.name }}